image: python:3.11

stages:
  - lint

flake8:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install pep8-naming
    - flake8 --verbose

django-check:
  stage: check
  script:
    - pip install -r requirements.txt
    - python manage.py check --deploy 2>&1 || true
    - python manage.py collectstatic --noinput
