# Generated by Django 5.2.11 on 2026-03-12 18:38

import django.db.models.deletion
import feedback.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "получено"),
                            ("in_progress", "в обработке"),
                            ("answered", "ответ дан"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="статус обработки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
            },
        ),
        migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=feedback.models.FeedbackFile.upload_to,
                        verbose_name="файл",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedback.feedback",
                        verbose_name="обратная связь",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл обратной связи",
                "verbose_name_plural": "файлы обратной связи",
            },
        ),
        migrations.CreateModel(
            name="FeedbackPersonData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="имя")),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="почта"),
                ),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person",
                        to="feedback.feedback",
                        verbose_name="обратная связь",
                    ),
                ),
            ],
            options={
                "verbose_name": "данные отправителя",
                "verbose_name_plural": "данные отправителей",
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время изменения"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("received", "получено"),
                            ("in_progress", "в обработке"),
                            ("answered", "ответ дан"),
                        ],
                        db_column="from",
                        max_length=20,
                        verbose_name="из статуса",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        choices=[
                            ("received", "получено"),
                            ("in_progress", "в обработке"),
                            ("answered", "ответ дан"),
                        ],
                        db_column="to",
                        max_length=20,
                        verbose_name="в статус",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="feedback.feedback",
                        verbose_name="обратная связь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог смены статуса",
                "verbose_name_plural": "логи смен статусов",
                "ordering": ("-timestamp",),
            },
        ),
    ]
