# Generated by Django 5.2.11 on 2026-03-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
            },
        ),
    ]
