# Generated by Django 5.2.11 on 2026-03-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackpersondata",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="имя"
            ),
        ),
    ]
