# Generated by Django 5.2.11 on 2026-03-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedback_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="имя"
            ),
        ),
    ]
