# Generated by Django 5.2.11 on 2026-03-12 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_feedback_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "получено"),
                    ("in_progress", "в обработке"),
                    ("answered", "ответ дан"),
                ],
                default="received",
                max_length=20,
                verbose_name="статус обработки",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(max_length=50, verbose_name="имя"),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время изменения"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("received", "получено"),
                            ("in_progress", "в обработке"),
                            ("answered", "ответ дан"),
                        ],
                        db_column="from",
                        max_length=20,
                        verbose_name="из статуса",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("received", "получено"),
                            ("in_progress", "в обработке"),
                            ("answered", "ответ дан"),
                        ],
                        db_column="to",
                        max_length=20,
                        verbose_name="в статус",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="feedback.feedback",
                        verbose_name="обратная связь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог смены статуса",
                "verbose_name_plural": "логи смен статусов",
                "ordering": ("-timestamp",),
            },
        ),
    ]
