# Generated by Django 5.2.11 on 2026-03-12 17:40

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_feedback_status_alter_feedback_name_statuslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackPersonData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="имя")),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="почта"),
                ),
            ],
            options={
                "verbose_name": "данные отправителя",
                "verbose_name_plural": "данные отправителей",
            },
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="name",
        ),
        migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=feedback.models.feedback_upload_to,
                        verbose_name="файл",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedback.feedback",
                        verbose_name="обратная связь",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл обратной связи",
                "verbose_name_plural": "файлы обратной связи",
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="person",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="feedback.feedbackpersondata",
                verbose_name="данные отправителя",
            ),
            preserve_default=False,
        ),
    ]
