# Generated by Django 5.2.11 on 2026-03-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_feedbackpersondata_remove_feedback_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="person",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="feedback.feedbackpersondata",
                verbose_name="данные отправителя",
            ),
        ),
    ]
