# Generated by Django 5.2.11 on 2026-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="кол-во неудачных входов"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="blocked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="заблокирован с"
            ),
        ),
    ]
