# Generated by Django 5.2.11 on 2026-03-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ненависть"),
                    (2, "Неприязнь"),
                    (3, "Нейтрально"),
                    (4, "Обожание"),
                    (5, "Любовь"),
                ],
                verbose_name="оценка",
            ),
        ),
    ]
