# Generated by Django 5.2.11 on 2026-02-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogcategory",
            name="normalized_name",
        ),
        migrations.RemoveField(
            model_name="catalogtag",
            name="normalized_name",
        ),
    ]
