# Generated by Django 5.2.11 on 2026-02-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Основная картинка товара",
                null=True,
                upload_to="items/main/",
                verbose_name="главное изображение",
            ),
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="items/gallery/", verbose_name="изображение"
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="alt",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение товара",
                "verbose_name_plural": "изображения товара",
                "ordering": ["ordering"],
            },
        ),
    ]
