# Generated by Django 5.2.11 on 2026-02-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0003_catalogcategory_normalized_name_and_more"),
        ("catalog", "0004_alter_catalogcategory_normalized_name_and_more"),
        ("catalog", "0005_alter_catalogcategory_normalized_name_and_more"),
    ]

    dependencies = [
        ("catalog", "0002_remove_catalogcategory_normalized_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogcategory",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                error_messages={
                    "unique": "Объект с похожим именем уже существует."
                },
                max_length=200,
                unique=True,
                verbose_name="normalized_name",
            ),
        ),
        migrations.AddField(
            model_name="catalogtag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                error_messages={
                    "unique": "Объект с похожим именем уже существует."
                },
                max_length=200,
                unique=True,
                verbose_name="normalized_name",
            ),
        ),
    ]
