# Generated by Django 5.2.11 on 2026-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_item_main_image_itemimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="items/main/",
                verbose_name="главное изображение",
            ),
        ),
    ]
