# Generated by Django 5.2.11 on 2026-02-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_catalogcategory_normalized_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogcategory",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                editable=False,
                error_messages={
                    "unique": "Объект с похожим именем уже существует."
                },
                max_length=200,
                null=True,
                unique=True,
                verbose_name="normalized_name",
            ),
        ),
        migrations.AlterField(
            model_name="catalogtag",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                editable=False,
                error_messages={
                    "unique": "Объект с похожим именем уже существует."
                },
                max_length=200,
                null=True,
                unique=True,
                verbose_name="normalized_name",
            ),
        ),
    ]
