# Generated by Django 5.2.11 on 2026-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="Статус отображения на главной.",
                verbose_name="на главной",
            ),
        ),
    ]
