# Generated by Django 5.2.11 on 2026-03-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_item_created_at_item_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="дата изменения"
            ),
        ),
    ]
