# Generated by Django 5.2.11 on 2026-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_item_created_at_alter_item_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemimage",
            name="alt",
        ),
        migrations.RemoveField(
            model_name="mainimage",
            name="alt",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Должен содержать только латинские буквы, цифры, дефисы и знаки подчёркивания",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Должен содержать только латинские буквы, цифры, дефисы и знаки подчёркивания",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
