# Generated by Django 5.2.11 on 2026-03-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_remove_itemimage_alt_remove_mainimage_alt_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
        migrations.AlterModelTable(
            name="item",
            table=None,
        ),
        migrations.AlterModelTable(
            name="tag",
            table=None,
        ),
    ]
